version: '3'

services: 
    selenium:
        image: nkovacs/selenium-standalone-phantomjs:latest
        restart: always
        ports:
            - 4444:4444
            - 5900:5900
        volumes:
            - ${DIRECTORY}:/appli
        networks: 
            - phpsrv

networks: 
    phpsrv: